name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Read .nvmrc
      id: node_version
      run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

    - uses: actions/setup-node@v2.1.5
      with:
        registry-url: 'https://npm.pkg.github.com'
        node-version: ${{ steps.node_version.outputs.NODE_VERSION }}

    - run: npm install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - run: npm run lint

    - run: npm run coverage
